-- MyUmrahGo production-ready MySQL schema for Hostinger.
-- No credentials or secrets belong in this file.
CREATE TABLE users (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, role ENUM('customer','agent','admin') NOT NULL DEFAULT 'customer', name VARCHAR(160) NOT NULL, email VARCHAR(190) UNIQUE NULL, phone VARCHAR(40) NULL, password_hash VARCHAR(255) NULL, status ENUM('active','pending','suspended') NOT NULL DEFAULT 'active', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE agencies (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, owner_user_id BIGINT UNSIGNED NOT NULL, name VARCHAR(190) NOT NULL, email VARCHAR(190) NULL, phone VARCHAR(40) NULL, status ENUM('pending','active','suspended') NOT NULL DEFAULT 'pending', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (owner_user_id) REFERENCES users(id)) ENGINE=InnoDB;
CREATE TABLE hotels (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, city ENUM('makkah','madinah') NOT NULL, name VARCHAR(190) NOT NULL, distance_m INT UNSIGNED NULL, stars TINYINT UNSIGNED NULL, description TEXT NULL, active TINYINT(1) NOT NULL DEFAULT 1, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE hotel_rates (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, hotel_id BIGINT UNSIGNED NOT NULL, room_type ENUM('sharing','quint','quad','triple','double','single') NOT NULL, sar_per_night DECIMAL(12,2) NOT NULL, valid_from DATE NULL, valid_to DATE NULL, FOREIGN KEY (hotel_id) REFERENCES hotels(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE flights (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, airline VARCHAR(120) NOT NULL, flight_no VARCHAR(30) NOT NULL, direction ENUM('outbound','return') NOT NULL, origin VARCHAR(8) NOT NULL, destination VARCHAR(8) NOT NULL, departure_at DATETIME NOT NULL, arrival_at DATETIME NOT NULL, baggage_kg INT UNSIGNED NULL, active TINYINT(1) NOT NULL DEFAULT 1) ENGINE=InnoDB;
CREATE TABLE packages (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(190) NOT NULL, slug VARCHAR(190) UNIQUE NOT NULL, duration_nights INT UNSIGNED NOT NULL, makkah_nights INT UNSIGNED NOT NULL, madinah_nights INT UNSIGNED NOT NULL, base_price_pkr DECIMAL(14,2) NULL, status ENUM('draft','published','archived') NOT NULL DEFAULT 'draft', description TEXT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE bookings (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, booking_no VARCHAR(40) UNIQUE NOT NULL, user_id BIGINT UNSIGNED NULL, agency_id BIGINT UNSIGNED NULL, package_id BIGINT UNSIGNED NULL, travellers INT UNSIGNED NOT NULL DEFAULT 1, room_type VARCHAR(30) NULL, status ENUM('inquiry','pending','confirmed','cancelled','completed') NOT NULL DEFAULT 'inquiry', total_pkr DECIMAL(14,2) NULL, notes TEXT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(id), FOREIGN KEY (agency_id) REFERENCES agencies(id), FOREIGN KEY (package_id) REFERENCES packages(id)) ENGINE=InnoDB;
CREATE TABLE wallet_transactions (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, agency_id BIGINT UNSIGNED NOT NULL, type ENUM('credit','debit') NOT NULL, amount_pkr DECIMAL(14,2) NOT NULL, reference VARCHAR(80) NULL, status ENUM('pending','approved','rejected') NOT NULL DEFAULT 'pending', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (agency_id) REFERENCES agencies(id)) ENGINE=InnoDB;
CREATE TABLE booking_documents (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, booking_id BIGINT UNSIGNED NOT NULL, type ENUM('voucher','invoice','other') NOT NULL, file_path VARCHAR(500) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (booking_id) REFERENCES bookings(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE audit_logs (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NULL, action VARCHAR(120) NOT NULL, entity_type VARCHAR(80) NULL, entity_id BIGINT UNSIGNED NULL, metadata JSON NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(id)) ENGINE=InnoDB;
CREATE INDEX idx_hotels_city_active ON hotels(city, active); CREATE INDEX idx_flights_dates ON flights(departure_at, active); CREATE INDEX idx_bookings_status ON bookings(status, created_at); CREATE INDEX idx_wallet_agency ON wallet_transactions(agency_id, created_at);
